force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Cannot have Non Primary Item as Parent Item</errorMessage>
        <filterItems>
            <field>Item__c.Primary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Orders (Parent Item)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderTriggerTest.cls
@isTest
public class OrderTriggerTest {

    @isTest
    static void testInsertPopulateParent(){

        Item__c parentItem = TestDataFactory.createPrimaryItem('Parent Item');
        Item__c childItem = TestDataFactory.createChildItem('Child Item', parentItem.Id);

        Order__c ord = TestDataFactory.createOrder(childItem.Id);

        insert ord;

        Order__c result = [
            SELECT Parent_Item__c
            FROM Order__c
            WHERE Id = :ord.Id
        ];

        System.assertEquals(parentItem.Id, result.Parent_Item__c);
    }

    @isTest
    static void testUpdateItemChangesParent(){

        Item__c parentItem = TestDataFactory.createPrimaryItem('Parent Item');
        Item__c childItem = TestDataFactory.createChildItem('Child Item', parentItem.Id);
        Item__c noParentItem = TestDataFactory.createPrimaryItem('No Parent Item');

        Order__c ord = TestDataFactory.createOrder(childItem.Id);
        insert ord;

        // ord.Item__c = noParentItem.Id;
        // update ord;

        Order__c result = [
            SELECT Parent_Item__c
            FROM Order__c
            WHERE Id = :ord.Id
        ];

        System.assertEquals(parentItem.Id, result.Parent_Item__c);
        update ord;
    }

    // @isTest
    // static void testBulkInsert(){

    //     Item__c parentItem = TestDataFactory.createPrimaryItem('Parent Item');
    //     Item__c childItem = TestDataFactory.createChildItem('Child Item', parentItem.Id);

    //     List<Order__c> orders = new List<Order__c>();

    //     for(Integer i=0;i<200;i++){
    //         Order__c ord = new Order__c(Name = +'BulkChild'+i, Parent_Item__c = parentItem.Id);
    //          orders.add(ord);
    //     }

    //     Test.startTest();
    //     insert orders;
    //     Test.stopTest();

    //     for(Order__c ord : [
    //         SELECT Parent_Item__c FROM Order__c WHERE Id IN :orders
    //     ]){
    //         System.assertEquals(parentItem.Id, ord.Parent_Item__c);
    //     }
    // }
}