force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Pricing__c/Vendor_Pricing__c.object-meta.xml
<CustomObject>
    <label>Vendor Pricing</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Pricing__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Vendor Pricings</relationshipLabel>
    <relationshipName>Vendor_Pricings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Pricing__c/fields/Parent_Item__c.field-meta.xml
<CustomField>
    <fullName>Parent_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Item</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Non Primary Item cannot be Parent Item</errorMessage>
        <filterItems>
            <field>Item__c.Primary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Vendor Pricings (Parent Item)</relationshipLabel>
    <relationshipName>Vendor_Pricings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vendor_Pricing__c/fields/Vendor_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Pricing__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;Id, Name &amp; &quot;_&quot; &amp; Item__r.Name &amp; &quot;_&quot; &amp; IF(ISBLANK(Vendor__c), &quot;&quot;, Vendor__r.Name), &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Pricing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VendorPricingTriggerTest.cls
@isTest
public class VendorPricingTriggerTest {

   @isTest
    static void testInsertPopulateParent(){

        Item__c parentItem = TestDataFactory.createPrimaryItem('Parent Item1');
        Item__c childItem = TestDataFactory.createChildItem('Child Item1', parentItem.Id);

        Vendor_Pricing__c vp = new Vendor_Pricing__c(
            
            Item__c = childItem.Id
        );

        insert vp;

        Vendor_Pricing__c result = [
            SELECT Parent_Item__c
            FROM Vendor_Pricing__c
            WHERE Id = :vp.Id
        ];

        System.assertEquals(parentItem.Id, result.Parent_Item__c);
    }

    @isTest
    static void testUpdateItemChangesParent(){

        Item__c parent1 = TestDataFactory.createPrimaryItem('Parent A');
        Item__c parent2 = TestDataFactory.createPrimaryItem('Parent B');

        Item__c child1 = TestDataFactory.createChildItem('Child A', parent1.Id);
        Item__c child2 = TestDataFactory.createChildItem('Child B', parent2.Id);

        Vendor_Pricing__c vp = new Vendor_Pricing__c(
           
            Item__c = child1.Id
        );

        insert vp;

        vp = [SELECT Parent_Item__c FROM Vendor_Pricing__c WHERE Id = :vp.Id];
        System.assertEquals(parent1.Id, vp.Parent_Item__c);

        vp.Item__c = child2.Id;
        update vp;

        vp = [SELECT Parent_Item__c FROM Vendor_Pricing__c WHERE Id = :vp.Id];

        System.assertEquals(parent2.Id, vp.Parent_Item__c);
    }

    @isTest
    static void testBulkInsert(){

        Item__c parentItem = TestDataFactory.createPrimaryItem('Parent Item3');
        Item__c childItem = TestDataFactory.createChildItem('Child Item3', parentItem.Id);

        List<Vendor_Pricing__c> records = new List<Vendor_Pricing__c>();

        for(Integer i = 0; i < 200; i++){
            records.add(new Vendor_Pricing__c(
                
                Item__c = childItem.Id
            ));
        }

        Test.startTest();
        insert records;
        Test.stopTest();

        for(Vendor_Pricing__c vp : [
            SELECT Parent_Item__c FROM Vendor_Pricing__c WHERE Id IN :records
        ]){
            System.assertEquals(parentItem.Id, vp.Parent_Item__c);
        }
    }
}