force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/At_Vendor__c.field-meta.xml
<CustomField>
    <fullName>At_Vendor__c</fullName>
    <label>At Vendor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Awaiting_Return__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_Return__c</fullName>
    <label>Awaiting Return</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Central_Spare__c.field-meta.xml
<CustomField>
    <fullName>Central_Spare__c</fullName>
    <label>Central Spare</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Excess_Spares_Good__c.field-meta.xml
<CustomField>
    <fullName>Excess_Spares_Good__c</fullName>
    <label>Excess Spares Good</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Failures_Repair__c.field-meta.xml
<CustomField>
    <fullName>Failures_Repair__c</fullName>
    <label>Failures Repair</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/In_Field__c.field-meta.xml
<CustomField>
    <fullName>In_Field__c</fullName>
    <label>In Field</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/IN_N_OUT__c.field-meta.xml
<CustomField>
    <fullName>IN_N_OUT__c</fullName>
    <label>IN-N-OUT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/In_Repair__c.field-meta.xml
<CustomField>
    <fullName>In_Repair__c</fullName>
    <label>In Repair</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Intransit_To_Depots__c.field-meta.xml
<CustomField>
    <fullName>Intransit_To_Depots__c</fullName>
    <label>Intransit To Depots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Item_Parent__c.field-meta.xml
<CustomField>
    <fullName>Item_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Item__c.Primary__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Local_Spares__c.field-meta.xml
<CustomField>
    <fullName>Local_Spares__c</fullName>
    <label>Local Spares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Order_180_Days__c.field-meta.xml
<CustomField>
    <fullName>Order_180_Days__c</fullName>
    <label>Order 180 Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Order_Next_Day__c.field-meta.xml
<CustomField>
    <fullName>Order_Next_Day__c</fullName>
    <label>Order Next Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Order_Same_Day__c.field-meta.xml
<CustomField>
    <fullName>Order_Same_Day__c</fullName>
    <label>Order Same Day</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Spare_3PL__c.field-meta.xml
<CustomField>
    <fullName>Spare_3PL__c</fullName>
    <label>Spare 3PL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Supplier_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Part_Number__c</fullName>
    <label>Supplier Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Total_Deployed__c.field-meta.xml
<CustomField>
    <fullName>Total_Deployed__c</fullName>
    <label>Total Deployed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Total_Required_Spares__c.field-meta.xml
<CustomField>
    <fullName>Total_Required_Spares__c</fullName>
    <label>Required Spares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Total_Spares__c.field-meta.xml
<CustomField>
    <fullName>Total_Spares__c</fullName>
    <label>Total Spares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Pricing__c/Vendor_Pricing__c.object-meta.xml
<CustomObject>
    <label>Vendor Pricing</label>
    <nameField>
        <displayFormat>VP-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Pricings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Pricing__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Vendor Pricings</relationshipLabel>
    <relationshipName>Vendor_Pricings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Pricing__c/fields/Vendor_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Pricing__c</fullName>
    <formula>HYPERLINK(&quot;/&quot;&amp;Id, Name &amp; &quot;_&quot; &amp; Item__r.Name &amp; &quot;_&quot; &amp; IF(ISBLANK(Vendor__c), &quot;&quot;, Vendor__r.Name), &quot;_blank&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendor Pricing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@IsTest
public class TestDataFactory {
    public static void createItems(Integer count){

        List<Item__c> items = new List<Item__c>();

        for(Integer i = 0; i < count; i++){

            items.add(new Item__c(
                Name = 'Item ' + i,
                Supplier_Part_Number__c = 'SP-' + i
            ));
        }

        insert items;
    }


    public static void createItemsForRepairBatch(){

        List<Item__c> items = new List<Item__c>();

        items.add(new Item__c(
            Name='Item Repair 1',
            Supplier_Part_Number__c=null,
            Failures_Repair__c=1
        ));

        items.add(new Item__c(
            Name='Item Repair 2',
            Supplier_Part_Number__c='SPN-1',
            Failures_Repair__c=10,
            Spare_3PL__c=1,
            Central_Spare__c=1,
          //  Spare_City__c=1,
            In_Repair__c=1,
            Awaiting_Return__c=1,
            Intransit_To_Depots__c=1
        ));

        items.add(new Item__c(
            Name='Item Recycle',
            Supplier_Part_Number__c='SPN-2',
            Failures_Repair__c=0,
            Spare_3PL__c=5,
            Central_Spare__c=5,
          //  Spare_City__c=5,
            Excess_Spares_Good__c=2
        ));

        items.add(new Item__c(
            Name='Item AWR',
            Supplier_Part_Number__c='SPN-3',
            Failures_Repair__c=0,
            Spare_3PL__c=5,
            Central_Spare__c=5,
          //  Spare_City__c=5,
            Excess_Spares_Good__c=0
        ));

        insert items;
    }

    /**
     * Creates and inserts a single primary Item__c (no Item_Parent__c).
     * Returns the inserted record with its Id populated.
     */
    public static Item__c createPrimaryItem(String name) {
    Item__c primary = new Item__c(
        Name = name,
        Primary__c = true  
    );
    insert primary;
    return primary;
}

    /**
     * Creates and inserts `count` secondary Item__c records under the given
     * primary, with all 14 rollup fields set to the supplied perItemValue.
     * Returns the inserted list.
     */
    public static List<Item__c> createSecondaryItemsForRollup(
            Id primaryId, Integer count, Decimal perItemValue) {

        List<Item__c> secondaries = new List<Item__c>();
        for (Integer i = 0; i < count; i++) {
            secondaries.add(new Item__c(
                Name                   = 'Secondary ' + (i + 1),
                Item_Parent__c         = primaryId,
                Order_Same_Day__c      = perItemValue,
                Order_Next_Day__c      = perItemValue,
                Order_180_Days__c      = perItemValue,
                Total_Deployed__c      = perItemValue,
                Total_Required_Spares__c = perItemValue,
                Total_Spares__c        = perItemValue,
                Local_Spares__c        = perItemValue,
                Central_Spare__c       = perItemValue,
                Stock__c               = perItemValue,
                In_Field__c            = perItemValue,
                IN_N_OUT__c            = perItemValue,
                Awaiting_Return__c= perItemValue,
                At_Vendor__c           = perItemValue,
                Intransit_To_Depots__c = perItemValue
            ));
        }
        insert secondaries;
        return secondaries;
    }
    
    

    // Create & insert CHILD Item
    public static Item__c createChildItem(String name, Id parentId){

        Item__c item = new Item__c(
            Name = name,
            Item_Parent__c = parentId//,Primary__c = false 
        );

        insert item;
        return item;
    }

    // Create item without parent
    public static Item__c createItemWithoutParent(String name){

        Item__c item = new Item__c(
            Name = name//,
            //Primary__c  = true // safe default
        );

        insert item;
        return item;
    }

    // Vendor Pricing (VALIDATED)
    public static Vendor_Pricing__c createAndInsertVendorPricing(Id itemId){

        System.assertNotEquals(null, itemId, 'Item Id cannot be null');

        Vendor_Pricing__c vp = new Vendor_Pricing__c(
    Item__c = itemId
        );

        insert vp;
        return vp;
    }

    public static Order__c createOrder(Id itemId){

        System.assertNotEquals(null, itemId, 'Item Id cannot be null');

        Order__c vp = new Order__c(
    Item__c = itemId
        );
        return vp;
    }


}