force-app/main/default/objects/Application_Config__mdt/Application_Config__mdt.object-meta.xml
<CustomObject>
    <label>Application Config</label>
    <pluralLabel>Application Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Application_Config__mdt/fields/Config_Value__c.field-meta.xml
<CustomField>
    <fullName>Config_Value__c</fullName>
    <label>Config Value</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Awaiting_Return__c.field-meta.xml
<CustomField>
    <fullName>Awaiting_Return__c</fullName>
    <label>Awaiting Return</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Central_Spare__c.field-meta.xml
<CustomField>
    <fullName>Central_Spare__c</fullName>
    <label>Central Spare</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Excess_Spares_Good__c.field-meta.xml
<CustomField>
    <fullName>Excess_Spares_Good__c</fullName>
    <label>Excess Spares Good</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Failures_Repair__c.field-meta.xml
<CustomField>
    <fullName>Failures_Repair__c</fullName>
    <label>Failures Repair</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/In_Repair__c.field-meta.xml
<CustomField>
    <fullName>In_Repair__c</fullName>
    <label>In Repair</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Intransit_To_Depots__c.field-meta.xml
<CustomField>
    <fullName>Intransit_To_Depots__c</fullName>
    <label>Intransit To Depots</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Local_Spares__c.field-meta.xml
<CustomField>
    <fullName>Local_Spares__c</fullName>
    <label>Local Spares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Repair_Action__c.field-meta.xml
<CustomField>
    <fullName>Repair_Action__c</fullName>
    <label>Repair Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Repair</fullName>
            </value>
            <value>
                <fullName>AWR</fullName>
            </value>
            <value>
                <fullName>Recycle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Required_Central_Spares__c.field-meta.xml
<CustomField>
    <fullName>Required_Central_Spares__c</fullName>
    <label>Required Central Spares</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Spare_3PL__c.field-meta.xml
<CustomField>
    <fullName>Spare_3PL__c</fullName>
    <label>Spare 3PL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Supplier_Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Part_Number__c</fullName>
    <label>Supplier Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchCalculateRepairAction.cls
global class BatchCalculateRepairAction implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc){
        String query;
        try{
            Application_Config__mdt config =[
                SELECT Config_Value__c
                FROM Application_Config__mdt
                WHERE DeveloperName = :AppConstants.BATCH_REPAIR_SOQL_CONFIG
                AND Active__c = true
                LIMIT 1
            ];

            if(config != null && String.isNotBlank(config.Config_Value__c)){
                query= config.Config_Value__c;
            }
        } catch(Exception ex){
            System.debug('BatchCalculateRepairAction | Metadata read failed: ' + ex.getMessage());
        }

        if(String.isBlank(query)){
            throw new AuraHandledException('BatchCalculateRepairAction: Missing SOQL configuration.');
        }
        return Database.getQueryLocator(query);
    }


    global void execute(Database.BatchableContext bc, List<SObject> scope){
        List<Item__c> recordsToUpdate = new List<Item__c>();

        for(SObject sob : scope) {
            Item__c item = (Item__c)sob;

            String calculatedRepairAction;

            // Rule 1: Missing Supplier Part Number
            if(String.isBlank(item.Supplier_Part_Number__c)) {
                calculatedRepairAction = AppConstants.REPAIR_ACTION_REPAIR;

            } else{

                Decimal availableSpares =
                    GenericUtility.nvl(item.Spare_3PL__c) +
                    GenericUtility.nvl(item.Central_Spare__c) +
                   // GenericUtility.nvl(item.Spare_City__c) +
                    GenericUtility.nvl(item.In_Repair__c) +
                    GenericUtility.nvl(item.Awaiting_Return__c) +
                    GenericUtility.nvl(item.Intransit_To_Depots__c);

                Boolean failureThresholdReached = GenericUtility.nvl(item.Failures_Repair__c) >= availableSpares;
                Boolean stockRequirementReached = (GenericUtility.nvl(item.Required_Central_Spares__c) + GenericUtility.nvl(item.Local_Spares__c)) >= availableSpares;

                if(failureThresholdReached || stockRequirementReached){
                    calculatedRepairAction = AppConstants.REPAIR_ACTION_REPAIR;
                
                } else if(item.Excess_Spares_Good__c != null && item.Excess_Spares_Good__c > 0){
                    calculatedRepairAction = AppConstants.REPAIR_ACTION_RECYCLE;
                    
                } else{
                    calculatedRepairAction = AppConstants.REPAIR_ACTION_AWR;

                }
            }

            if(item.REPAIR_ACTION__c != calculatedRepairAction) {
                item.REPAIR_ACTION__c = calculatedRepairAction;
                recordsToUpdate.add(item);
            }
        }

  
        if(!recordsToUpdate.isEmpty()) {
            Database.SaveResult[] results = Database.update(recordsToUpdate, false);

            for(Integer i = 0; i < results.size(); i++){
                if(!results[i].isSuccess()){

                    for (Database.Error err : results[i].getErrors()) {
                        System.debug('BatchCalculateRepairAction | DML Error | RecordId: ' + recordsToUpdate[i].Id + ' | Message: ' + err.getMessage());
                    }
                }
            }
        }
    }


    global void finish(Database.BatchableContext bc) {
        System.debug('BatchCalculateRepairAction completed successfully.');
         String switchForChaining;
        try{
            Application_Config__mdt config =[
                SELECT Config_Value__c
                FROM Application_Config__mdt
                WHERE DeveloperName = 'ItemCSVBatchChainingSwitch'
                AND Active__c = true
                LIMIT 1
            ];

            if(config != null && String.isNotBlank(config.Config_Value__c)){
                 switchForChaining = config.Config_Value__c;
            }
        } catch(Exception ex){
            System.debug('BatchCalculateRepairAction | Metadata read failed: ' + ex.getMessage());
        }
        if(switchForChaining == 'ON'){
            Database.executeBatch(new ItemCSVBatch(), AppConstants.DEFAULT_BATCH_SIZE);
        }
        else {
            System.debug('Dont call ItemCSVBatch in chaining');
        }
    
    }
       
}